apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: nginx-interno-deployment
  namespace: default 
spec:
  selector:
    matchLabels:
      app: nginx-interno
  replicas: 1 # Actualiza el número de réplicas de 2 a 4
  template:
    metadata:
      labels:
        app: nginx-interno
    spec:
      containers:
      - name: nginx-interno
        image: nginx:alpine
        ports:
        - containerPort: 80
---
---
# https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-interno
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-interno
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
