# File: .github/workflows/workflow.yml
on: [push]

name: cicd_pipeline

jobs:

  cicd_flow:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@master
      
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: "Create devlopment environments namespace"
        uses: okteto/create-namespace@latest
        with:
          namespace: unlu-demo
      
      - name: GitHub Login
        uses: actions-hub/docker/login@master
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}