# File: .github/workflows/workflow.yml
# Okteto documentation: https://www.okteto.com/docs/cloud/github-actions/
# 
on: [push]

name: cicd_pipeline

jobs:

  cicd_flow:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@master
      
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: "Create deployment"
        uses: okteto/apply@master
        with:
          manifest: okteto_k8s_github_actions/yamls/deployment.yaml
      
    


   
          