# File: .github/workflows/workflow.yml
# Okteto documentation: https://www.okteto.com/docs/cloud/github-actions/
# 
on: [push]

name: cicd_pipeline

jobs:

  cicd_flow:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@master
      
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f .okteto_k8s_github_actions/yamls/deployment.yaml
    


   
          