# File: .github/workflows/workflow.yml
on: [push]

name: cicd_pipeline

jobs:

  cicd_flow:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout code
        uses: actions/checkout@master
      
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
      - name: "Create devlopment environments namespace"
        uses: okteto/create-namespace@latest
        with:
          namespace: development
          
      
      # - name: GitHub Login
      #   uses: actions-hub/docker/login@master
      #     env:
      #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build :latest
      #   if: success()
      #   run: docker build -t docker.pkg.github.com/${{ github.repository }}/app:latest .
        
      # - name: Push to docker hub :latest
      #   if: success()
      #   uses: actions-hub/docker@master
      #   with:
      #     args: push docker.pkg.github.com/${{ github.repository }}:latest
      
   
          